#!/usr/bin/fish

if [ (count $argv) -ne 1 ]
    echo "usage: "(basename (status -f))" symbol"
    exit 1
end

while [ (pwd) != $HOME -a (pwd) != / -a ! -e ./tags ]
    cd ..
end

if [ ! -e ./tags ]
    echo "no tags file found"
    exit 1
end

ag --vimgrep -s -f $argv[1] --ignore 'man' --ignore '*.html'
