#!/bin/bash

timer_file=~/.timer

start_timer() {
    date +%s >${timer_file}
}

reset_timer() {
    rm -f ${timer_file}
}

show_elapsed() {
    if [ -r ${timer_file} ]; then
	stime=$(< ${timer_file})
	now=$(date +%s)
	elapsed=$((now - stime))

	min=$((elapsed / 60))
	[ ${min} -gt 50 ] && suf='!' || suf=''
	hr=$((min / 60))
	min=$((min - 60*hr))

	printf "timer: %d:%02d%c\n" ${hr} ${min} ${suf}
    else
	printf "(no timer)\n"
    fi
}

case "$1" in
    -e|--elapsed) # show elapsed time
    show_elapsed
    ;;

    -r|--reset) # stop (and reset) timer
    reset_timer
    ;;

    -s|--start) # start (or restart) timer
    start_timer
    ;;
esac
